# Generated by Django 5.0.7 on 2024-07-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
